ALTER TABLE "EndpointUser" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "PolicyAssignment" ALTER COLUMN "updatedAt" DROP DEFAULT;
ALTER TABLE "PolicyDelivery" ALTER COLUMN "updatedAt" DROP DEFAULT;
