export const riskLevels = ["low", "medium", "high", "critical"] as const;
export const actions = ["detected", "scanned", "allowed", "warned", "blocked", "redacted", "replaced", "user_override", "failed", "unsupported"] as const;
export const inputTypes = ["prompt", "file_upload", "app_usage", "policy", "desktop_app", "browser"] as const;
export const pluginEventTypes = [
  "genai_app_detected",
  "genai_app_used",
  "prompt_scanned",
  "sensitive_prompt_detected",
  "prompt_blocked",
  "prompt_warned",
  "prompt_allowed",
  "prompt_replaced_with_safe_prompt",
  "prompt_allowed_after_safe_replacement",
  "prompt_user_override",
  "file_attached",
  "file_scan_started",
  "file_scanned",
  "sensitive_file_detected",
  "sensitive_file_upload_detected",
  "file_upload_blocked",
  "file_upload_warned",
  "file_upload_allowed",
  "file_scan_failed",
  "unsupported_file_type_detected",
  "unknown_genai_app_detected",
  "policy_applied",
  "policy_sync_failed",
  "plugin_update_available"
] as const;
export const policyModes = ["monitor", "passive", "active"] as const;
export const policyActions = ["allow", "warn", "block", "redact"] as const;
export const appTypes = ["browser", "desktop", "browser_and_desktop"] as const;
export const approvedStatuses = ["approved", "restricted", "blocked", "unknown"] as const;

export const sensitiveCategories = [
  "business_general",
  "internal_low_risk",
  "email",
  "phone",
  "customer_name",
  "government_id",
  "national_id",
  "tax_id",
  "driver_license",
  "passport",
  "date_of_birth",
  "postal_address",
  "bank_account",
  "routing_number",
  "sort_code",
  "iban",
  "swift_bic",
  "upi_id",
  "crypto_wallet",
  "payment_card",
  "api_key",
  "access_token",
  "secret_key",
  "password",
  "private_key",
  "token",
  "aadhaar",
  "pan",
  "database_connection",
  "medical_record",
  "patient_id",
  "insurance_id",
  "employee_id",
  "account_id",
  "business_sensitive",
  "custom_sensitive_term",
  "contract_value"
] as const;

export const forbiddenTelemetryFieldNames = [
  "rawPrompt",
  "promptText",
  "prompt",
  "fileContent",
  "fileText",
  "documentText",
  "fileBytes",
  "rawFile",
  "rawFileContent",
  "documentContent",
  "extractedText",
  "ocrText",
  "screenshot",
  "secretValue",
  "secret",
  "password",
  "passwordValue",
  "apiKey",
  "apiKeyValue",
  "token",
  "tokenValue",
  "privateKey",
  "piiValue",
  "detectedValue",
  "rawValue"
] as const;
